import OpenAI from 'openai'
import { zodTextFormat } from 'openai/helpers/zod'
import { z } from 'zod'
import { contentScore } from './scoring'
import type { ContentResult } from './types'

const Score = z.int().min(0).max(100)
const Schema = z.object({
  vocabulary_score: Score,
  topic_score: Score,
  grammar_score: Score,
  is_off_topic: z.boolean(),
  strengths: z.string(),
  improvements: z.string(),
  corrections: z.array(z.object({ original: z.string(), corrected: z.string(), explanation: z.string() })),
  improved_answer: z.string(),
})

const INSTRUCTIONS = `You are an English teacher evaluating spoken responses to topics. Score this response on vocabulary, topic relevance, and grammar, each 0-100.

Criteria:
- vocabulary_score: range, precision, collocation and appropriacy of word choice.
- topic_score (topic relevance): answers the topic/question, develops ideas with details/examples, coherence and use of linking devices.
- grammar_score: range and accuracy of structures: tense, agreement, word order, articles/prepositions, sentence structure.

The transcript is generated by a Speech-to-Text engine. Ignore punctuation/capitalisation. DO NOT mention typographical or spelling mistakes. Treat nonsensical words as STT artifacts, never as evidence of errors.

If the response is completely off-topic, irrelevant, or only a few meaningless words: is_off_topic = true and every score ≤ 20.

Feedback rules:
- strengths and improvements: in Vietnamese, concise, 1-3 sentences each, quoting the learner's exact phrases.
- corrections: up to 5, most important first; "original" is the learner's exact phrase, "corrected" the fixed English, "explanation" in Vietnamese.
- improved_answer: in English; keep the learner's ideas, natural spoken English, roughly the same length (at most +20%).
- Never state numeric scores in the text fields.`

const EXAMPLES = `Calibration examples for the topic "How has technology changed communication?":

Good response (vocabulary_score 80, topic_score 85, grammar_score 85):
"I think technology has drastically changed how we communicate in the past decade. Smartphones allow us to instantly connect with anyone globally. Social media platforms have created new ways to share experiences. Video calls make distance less important. However, these changes aren't all positive. Many people feel constantly distracted by notifications, and face-to-face interaction has decreased. Overall, while technology offers amazing connectivity, we need to find balance in how we use it."

Average response (vocabulary_score 60, topic_score 55, grammar_score 50):
"Technology changed communication a lot. We use phones to talk to people and social media is very popular now. People can make video calls to see other people. But sometimes technology is not good because people look at phones all the time. Some people don't like to talk face to face anymore. I think technology is good but we shouldn't use it too much."

Poor response (vocabulary_score 30, topic_score 35, grammar_score 25):
"Technology is good for communication. I like phone. I can call my friend. Social media is also good. I use Facebook. Sometimes I don't like technology. People always use phone. I think technology have good and bad things."`

const clamp = (n: number) => Math.min(100, Math.max(0, Math.round(n)))

// GPT-5 family: no temperature parameter.
export async function assessContent(topic: string, transcript: string): Promise<ContentResult> {
  const client = new OpenAI({ timeout: 60_000, maxRetries: 1 })
  const response = await client.responses.parse({
    model: process.env.OPENAI_MODEL || 'gpt-5-mini',
    reasoning: { effort: 'low' },
    instructions: INSTRUCTIONS,
    input: `${EXAMPLES}\n\nNow evaluate this response to the topic "${topic}":\n"${transcript}"`,
    text: { format: zodTextFormat(Schema, 'speaking_content') },
  })
  const out = response.output_parsed
  if (!out) throw new Error('OpenAI returned no parsed content assessment')

  const vocabulary = clamp(out.vocabulary_score)
  const topicScore = clamp(out.topic_score)
  const grammar = clamp(out.grammar_score)
  return {
    vocabulary,
    topic: topicScore,
    grammar,
    content: contentScore(vocabulary, topicScore, grammar),
    isOffTopic: out.is_off_topic,
    strengths: out.strengths,
    improvements: out.improvements,
    corrections: out.corrections.slice(0, 5),
    improvedAnswer: out.improved_answer,
  }
}
